name: Release
on:
  push:
    branches: [develop, main]
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v4
        with: { version: 10.9.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile

      - name: Set publish command
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/develop" ]; then
            echo "PUBLISH_CMD=pnpm changeset publish --provenance --tag next" >> $GITHUB_ENV
          else
            echo "PUBLISH_CMD=pnpm changeset publish --provenance" >> $GITHUB_ENV
          fi

      - name: Create or Publish Release
        uses: changesets/action@v1
        with:
          publish: ${{ env.PUBLISH_CMD }}
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
