name: Verify Changeset
on:
  pull_request:
    branches: [develop, main]

permissions:
  contents: read
  pull-requests: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check override label
        id: labelcheck
        uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.pull_request?.labels || []).map(l => l.name);
            core.setOutput('has_label', labels.includes('no-release'));

      - name: Fail if no changeset
        if: steps.labelcheck.outputs.has_label != 'true'
        run: |
          if [ -z "$(ls -1 .changeset/*.md 2>/dev/null)" ]; then
            echo "No changeset found. Add one with 'pnpm changeset' or label this PR with 'no-release'."
            exit 1
          fi
